### ISSUE TITLE
 How to format an input 1D extracted spectrum fits file

### ISSUE THREAD

**Issue by jensjessenhansen** [gmbrandt/xwavecal#6]
Hi Mirek,
This is not really an issue but more a user support question.
I'm trying to apply xwavecal to 1D extracted spectra from the SONG spectrograph. These have a different format and I have tried to convert a ThAr file into a format xwavecal understands.

The SONG spectrograph is a Coude fed slit echelle spectrograph and has only one spectrum per diffraction order. I have made a test ThAr fits file with the 20 bluest orders which have some overlap  (should be diffraction orders 118-138). But when I try calibrating it xwavecal fails in the 'IdentifyFibers' stage and unfortunately I cannot figure out what I'm doing wrong. Hopefully, you can help me out when you have time.
The traceback is further below. 

The fits file and the config.ini file I used are here: [https://github.com/jensjessenhansen/xwavecal/blob/fitsconversion/xwavecal/examples/data/thar_s1_2018-10-27T17-48-01_xwavecal_fmt.fits](url) and [https://github.com/jensjessenhansen/xwavecal/blob/fitsconversion/xwavecal/examples/SONG_config.ini](url)

As far as I can tell the ThAr file has a format matching what is described in README.rst.
Here's how it looks:

    >>>from astropy.io import fits
    >>>from astropy.table import table

    >>>ff = fits.open('thar_s1_2018-10-27T17-48-01_xwavecal_fmt.fits')
    >>>ff.info()
    Filename: thar_s1_2018-10-27T17-48-01_xwavecal_fmt.fits
    No.    Name      Ver    Type      Cards   Dimensions   Format
      0  PRIMARY       1 PrimaryHDU      15   (2048, 2048)   float64   
      1  SPECBOX       1 BinTableHDU     23   20R x 7C   [K, 2048D, 2048D, 2048K, K, D, 2048D]   
      2  BLZCORR       1 BinTableHDU     23   20R x 7C   [K, 2048D, 2048D, 2048K, K, D, 2048D]   

    >>>spec = table.Table(ff['BLZCORR'].data) 
    >>>print(spec)                                                                                                                                                                                               
     id                 flux [2048]                                 stderr [2048]                  pixel [2048] fiber ref_id wavelength [2048]
    --- ------------------------------------------- ---------------------------------------------- ------------ ----- ------ -----------------
      0     0.091946439594712 .. 0.5818774748125423  0.0019891454055756953 .. 0.004626625914857271    0 .. 2047     0    nan        nan .. nan
      1  0.07289896138147353 .. 0.10225059329599062 0.0018390645120301369 .. 0.0019896780557858065    0 .. 2047     0    nan        nan .. nan
    .......
     19  0.22136406290758737 .. 0.12066329786328694   0.009773252245673254 .. 0.004794921371721589    0 .. 2047     0    nan        nan .. nan
    
And I have just attached a minimal header with keywords similar to in the nres test data set and config file.
  
    >>>ff[0].header                                                                                                                                                                                               
    SIMPLE  =                    T / conforms to FITS standard                      
    BITPIX  =                  -64 / array data type                                
    NAXIS   =                    2 / number of array dimensions                     
    NAXIS1  =                 2048                                                  
    NAXIS2  =                 2048                                                  
    EXTEND  =                    T                                                  
    OBSTYPE = 'wavecal '                                                            
    GAIN    =                  1.0                                                  
    RDNOISE =                  9.5                                                  
    OBJECTS = 'thar&none&none'                                                      
    DATE-OBS= '2018-10-27T17:48:01.461717'                                          
    TELESCOP= 's1      '                                                            
    INSTRUME= 'Spectrograph'                                                        
    SITEID  = 'Teide   '                                                            
    FRAMENUM= '1       '                        

This is the traceback I get when I try running 

    >>>xwavecal_reduce --data-paths /home/jensjh/uni/SONG/xwavecal_test/test.fits --output-dir ~/Downloads --config-file /home/jensjh/uni/code/xwavecal/xwavecal/examples/SONG_config.ini 
    2019-10-25 16:22:50,404 - xwavecal.main - reduce_data - INFO - Reducing /home/jensjh/uni/SONG/xwavecal_test/test.fits assuming a data class of xwavecal.images.Image and raw data in extension 0
    2019-10-25 16:22:50,882 - MakeFiberTemplate - do_stage - INFO - Generating a template with center order 10
    2019-10-25 16:22:50,898 - xwavecal.images - write - INFO - Writing file to /home/jensjh/Downloads/Teide_SONG1_20181027_some_unique_id_fibers_100.fits
    2019-10-25 16:22:50,923 - xwavecal.main - write_out - INFO - Adding file to processed image database at /home/jensjh/Downloads/pipeline1.db
    2019-10-25 16:22:50,949 - IdentifyFibers - do_stage - INFO - Template/calibration loaded: /home/jensjh/Downloads/Teide_SONG1_20181027_some_unique_id_fibers_100.fits
    2019-10-25 16:22:50,949 - IdentifyFibers - apply_master_calibration - INFO - Identifying fibers via cross correlation.
    Traceback (most recent call last):
      File "/home/jensjh/Programs/anaconda3/envs/xwave/bin/xwavecal_reduce", line 8, in <module>
    sys.exit(reduce_data())
      File "/home/jensjh/uni/code/xwavecal/xwavecal/main.py", line 52, in reduce_data
    data = stage(runtime_context).do_stage(data)
      File "/home/jensjh/uni/code/xwavecal/xwavecal/stages.py", line 36, in do_stage
    return self.apply_master_calibration(image, master_calibration_path)
      File "/home/jensjh/uni/code/xwavecal/xwavecal/fibers.py", line 69, in apply_master_calibration
    num_lit_fibers=image.num_lit_fibers())
      File "/home/jensjh/uni/code/xwavecal/xwavecal/fibers.py", line 111, in construct_single_fiber_template
    template[::num_lit_fibers] = single_fiber
    ValueError: could not broadcast input array from shape (3,2048) into shape (2,2048)

I wrote OBJECTS = 'thar&none&none' in the header and used 0 as fiber number in the 'fiber' column. As far as I understand from the readme this is what I should do in this case.

**Comment by gmbrandt** [comment]
Hello,

I have just now sent you an email. As far as I can tell, the input data is perfect. This is an issue in the code that spectrographs with 1 fiber are not properly handled in the identify fibers stage. I will work on this. Thank you for bringing up the issue.

Best,

Mirek

**Comment by gmbrandt** [comment]
Also, as a quick hotfix. You may forgo the fiber identification stage provided that you populate the ref_id column of your input spectrum. e.g. just with np.arange(min_order, max_order). identify fibers simply populates the fiber and ref_id columns. I see you already have the fiber column populated. If fiber and ref_id are populated, comment out the IdentifyFibers Stage in your config.ini

**Comment by gmbrandt** [comment]
Hi Jens, I believe I have resolved this issue in PR #9 .

**Comment by gmbrandt** [comment]
Assumed this is resolved in PR #9
